#!/usr/bin/env node

const program = require('commander');
const fs = require('fs');
const path = require('path');
const low = require('lowdb');
const FileSync = require('lowdb/adapters/FileSync');
const CLIENT_DB_PATH = path.join(__dirname, 'client-db');
const {
  getTransactions,
  getTxInfo,
  getSwapRates,
  getChainID,
  addressGenerator,
  getValidatorInfo,
} = require('../dist/src');

const { TerraThreshSigClient } = require('../dist/src');
const client = new TerraThreshSigClient();

const terra = require('@terra-money/terra.js');

function ensureDirSync(dirpath) {
  try {
    fs.mkdirSync(dirpath, { recursive: true });
  } catch (err) {
    if (err.code !== 'EEXIST') throw err;
  }
}

program
  .command('address')
  .option('-i, --index [index]', 'Address index')
  .action(async (options) => {
    await client.init();
    const address = client.getAddress(options.index);
    console.log(address);
  });

program
  .command('balance <address>')
  .option('-n, --network [name]', 'Name of network ("soju", "columbus_3")')
  .action(async (address, options) => {
    await client.init(options.network);
    console.log(await client.getBalance(address, options.network || 'tequila'));
  });

program
  .command('pending_rewards <address>')
  .option('-n, --network [name]', 'Name of network ("soju", "columbus_3")')
  .action(async (address, options) => {
    await client.init(options.network);
    console.log(
      JSON.stringify(
        await client.getPendingRewards(address, options.network || 'tequila'),
        null,
        2,
      ),
    );
  });

program
  .command('validator_stats <address>')
  .option(
    '-n, --network [name]',
    'Name of network ("soju", "columbus", "tequila")',
  )
  .action(async (address, options) => {
    console.log(await getValidatorInfo(address, options.network || 'tequila'));
  });

program
  .command('delegations <address>')
  .option(
    '-n, --network [name]',
    'Name of network ("soju", "columbus", "tequila")',
  )
  .action(async (address, options) => {
    await client.init(options.network);
    console.log(
      await client.getDelegations(address, options.network || 'tequila'),
    );
  });

program
  .command('rates')
  .option(
    '-d, --denom [symbol]',
    'denomination of the transfer ("uluna" default, "uusd", ...)',
  )
  .option('-n, --network [name]', 'Name of network ("soju" or "columbus_3")')
  .action(async (options) => {
    await client.init(options.network);
    console.log(
      await getSwapRates(options.denom || 'uluna', options.network || 'soju'),
    );
  });

program.command('generate').action(() => {
  addressGenerator();
});

program
  .command('tx_info <txhash>')
  .option('-n, --network [name]', 'Name of network ("soju" or "columbus_3")')
  .action(async (txhash, options) => {
    console.log(await getTxInfo(txhash, options.network || 'soju'));
  });

program
  .command('transactions')
  .option('-a --account <account>', 'Account address')
  .option('-p --page <page>', 'Page number')
  .option('-l --limit <limit>', 'Page limit')
  .option('-n, --network [name]', 'Name of network ("soju" or "columbus-3')
  .action(async (options) => {
    const txs = await getTransactions(options);
    console.log(JSON.stringify(txs, null, 2));
  });

program
  .command('chain_id')
  .option('-n, --network [name]', 'Name of network ("soju" or "columbus-3')
  .action(async (options) => {
    const chainID = await getChainID(options.network || 'columbus');
    console.log(chainID);
  });

program
  .command('transfer <from> <to> <amount>')
  .option(
    '-d, --denom [symbol]',
    'denomination of the transfer ("luna" default, "usd", ...)',
  )
  .option('-n, --network [name]', 'Name of network ("soju" or "columbus_3")')
  .option('-dr, --dry_run', 'Print the tx without posting it')
  .option('-sa, --send_async', 'Send tx asynchronously, deafult = false')
  .option('-all, --all', 'Transfer all the coins of the specified currency')
  .action(async (from, to, amount, options) => {
    await client.init(options.network);
    let sendOptions = {
      memo: options.memo,
      chainName: options.network,
    };
    let res = await client.transfer(
      from,
      to,
      amount,
      options.denom || 'uluna',
      sendOptions,
      options.all,
      !options.send_async,
      options.dry_run,
    );
    console.log('Result', res);
  });

program
  .command('collect_rewards <delegator> <validator> ')
  .option(
    '-d, --denom [symbol]',
    'denomination of the transfer ("luna" default, "usd", ...)',
  )
  .option('-n, --network [name]', 'Name of network ("soju" or "columbus_3")')
  .option('-dr, --dry_run', 'Print the tx without posting it')
  .option('-sa, --send_async', 'Send tx asynchronously, deafult = false')
  .option('-all, --all', 'Transfer all the coins of the specified currency')
  .action(async (delegator, validator, options) => {
    await client.init(options.network);
    let sendOptions = {
      memo: options.memo,
      chainName: options.network,
    };
    let res = await client.collectRewards(
      delegator,
      validator,
      sendOptions,
      options.all,
      !options.send_async,
      options.dry_run,
    );
    console.log('Result', res);
  });

program
  .command('delegate <from> <to> <amount>')
  .option(
    '-d, --denom [symbol]',
    'denomination of the transfer ("luna" default, "usd", ...)',
  )
  .option('-n, --network [name]', 'Name of network ("soju" or "columbus_3")')
  .option('-dr, --dry_run', 'Print the tx without posting it')
  .option('-all, --all', 'Transfer all the coins of the specified currency')
  .action(async (from, to, amount, options) => {
    await client.init(options.network);
    let sendOptions = {
      memo: options.memo,
      chainName: options.network,
    };
    let res = await client.delegate(
      from,
      to,
      amount,
      options.denom || 'uluna',
      sendOptions,
      options.all,
      true,
      options.dry_run,
    );
    console.log('Result', res);
  });

program
  .command('redelegate <from> <validator_src> <validator_dst> <amount>')
  .option(
    '-d, --denom [symbol]',
    'denomination of the transfer ("luna" default, "usd", ...)',
  )
  .option('-n, --network [name]', 'Name of network ("soju" or "columbus_3")')
  .option('-dr, --dry_run', 'Print the tx without posting it')
  .option('-all, --all', 'Transfer all the coins of the specified currency')
  .action(async (from, validator_src, validator_dst, amount, options) => {
    await client.init(options.network);
    let sendOptions = {
      memo: options.memo,
      chainName: options.network,
    };
    let res = await client.redelegate(
      from,
      validator_src,
      validator_dst,
      amount,
      options.denom || 'uluna',
      false,
      options.dry_run,
    );
    console.log('Result', res);
  });

program
  .command('undelegate <from> <to> <amount>')
  .option(
    '-d, --denom [symbol]',
    'denomination of the transfer ("luna" default, "usd", ...)',
  )
  .option('-n, --network [name]', 'Name of network ("soju" or "columbus_3")')
  .option('-dr, --dry_run', 'Print the tx without posting it')
  .option('-all, --all', 'Transfer all the coins of the specified currency')
  .action(async (from, to, amount, options) => {
    await client.init(options.network);
    let sendOptions = {
      memo: options.memo,
      chainName: options.network,
    };
    let res = await client.undelegate(
      from,
      to,
      amount,
      options.denom || 'uluna',
      sendOptions,
      options.all,
      true,
      options.dry_run,
    );
    console.log('Result', res);
  });

program
  .command('swap <from> <amount> <ask>')
  .option(
    '-d, --denom [symbol]',
    'denomination of the transfer ("luna" default, "usd", ...)',
  )
  .option('-n, --network [name]', 'Name of network ("soju" or "columbus_3")')
  .option('-dr, --dry_run', 'Print the tx without posting it')
  .action(async (from, amount, ask, options) => {
    await client.init(options.network);
    let sendOptions = {
      memo: options.memo,
      chainName: options.network,
    };
    let res = await client.swap(
      from,
      amount,
      options.denom || 'uluna',
      options.ask || 'uusd',
      sendOptions,
      options.dry_run,
    );
    console.log('Result', res);
  });

program.parse(process.argv);
